# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubOverview < Formula
  desc "Local command center dashboard for monitoring multiple GitHub repositories"
  homepage "https://github.com/toshon-jennings/github-overview"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toshon-jennings/github-overview/releases/download/v0.1.1/github-overview_0.1.1_darwin_amd64.tar.gz"
      sha256 "93e5058c2a95e7ae2a81070b403076b6c48208fae8f02273d0b238836fb7683e"

      define_method(:install) do
        bin.install "github-overview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toshon-jennings/github-overview/releases/download/v0.1.1/github-overview_0.1.1_darwin_arm64.tar.gz"
      sha256 "568e2a9a881e2f278f94e3558da841b99db0f1b25a5770d2d0b627b5f3b8e213"

      define_method(:install) do
        bin.install "github-overview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toshon-jennings/github-overview/releases/download/v0.1.1/github-overview_0.1.1_linux_amd64.tar.gz"
      sha256 "877a5c34816c78491480c61938801f2d9d2678c353fa5f5c775870bcbece8637"
      define_method(:install) do
        bin.install "github-overview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toshon-jennings/github-overview/releases/download/v0.1.1/github-overview_0.1.1_linux_arm64.tar.gz"
      sha256 "ae50620787ac777a07f3c85a89bbce5b41f1871272858e82558c1b1d13863025"
      define_method(:install) do
        bin.install "github-overview"
      end
    end
  end

  test do
    system "#{bin}/github-overview", "--help"
  end
end
