# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubOverview < Formula
  desc "Local command center dashboard for monitoring multiple GitHub repositories"
  homepage "https://github.com/toshon-jennings/github-overview"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toshon-jennings/github-overview/releases/download/v0.1.1/github-overview_0.1.1_darwin_amd64.tar.gz"
      sha256 "12b256aa7094b20942102dfdaf0a1ea6a635ebbf2870a21abe89b99de7d42133"

      define_method(:install) do
        bin.install "github-overview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toshon-jennings/github-overview/releases/download/v0.1.1/github-overview_0.1.1_darwin_arm64.tar.gz"
      sha256 "f9a6500c2b6d93f0444af41ead9536c99cc22103527982faf284e72ffedc6f19"

      define_method(:install) do
        bin.install "github-overview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toshon-jennings/github-overview/releases/download/v0.1.1/github-overview_0.1.1_linux_amd64.tar.gz"
      sha256 "14ed59a0eb561c94960b112b5adf18ad9b82868b1acc2a165248f0d97d2b1100"
      define_method(:install) do
        bin.install "github-overview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toshon-jennings/github-overview/releases/download/v0.1.1/github-overview_0.1.1_linux_arm64.tar.gz"
      sha256 "840a7c2362cc1f2717487da25e247df04f8a1d4c110fd67b6ffafb31b4050d2c"
      define_method(:install) do
        bin.install "github-overview"
      end
    end
  end

  test do
    assert_match "no repos tracked", shell_output("#{bin}/github-overview list -db #{testpath}/test.db")
  end
end
