# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline. DO NOT EDIT.
class OcRig < Formula
  desc "OC Rig — community fork of the AI coding agent for the terminal."
  homepage "https://github.com/toshon-jennings/opencode-rig"
  version "0.1.197"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toshon-jennings/opencode-rig/releases/download/v0.1.197/opencode-darwin-x64.zip"
      sha256 "8e04269ef57ad99e5f619c3b2322be9cb440742090f05a794113c137e59d4096"

      def install
        bin.install "opencode" => "oc-rig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toshon-jennings/opencode-rig/releases/download/v0.1.197/opencode-darwin-arm64.zip"
      sha256 "68c1940036827dcaebbc201beb8610b06ae7dce68c6b66c281fb22c18155b5c5"

      def install
        bin.install "opencode" => "oc-rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/toshon-jennings/opencode-rig/releases/download/v0.1.197/opencode-linux-x64.tar.gz"
      sha256 "39f6eec4b973a56c9bd2990bdfb80f643a4a0ee3376708ac810510476543b070"
      def install
        bin.install "opencode" => "oc-rig"
      end
    end
  end
end
